flasher: magisk: update to official Magisk v18.0
Signed-off-by: kdrag0n <dragon@khronodragon.com>

diff --git a/flasher/magisk/META-INF/com/google/android/updater-script b/flasher/magisk/META-INF/com/google/android/updater-script
--- a/flasher/magisk/META-INF/com/google/android/updater-script
+++ b/flasher/magisk/META-INF/com/google/android/updater-script
@@ -14,14 +14,17 @@
 ##########################################################################################
 
 COMMONDIR=$INSTALLER/common
+APK=$COMMONDIR/magisk.apk
+CHROMEDIR=$INSTALLER/chromeos
 
 # Default permissions
 umask 022
 
 OUTFD=$2
+ZIP=$3
 
 if [ ! -f $COMMONDIR/util_functions.sh ]; then
-  echo " ! Unable to extract zip file!"
+  echo "! Unable to extract zip file!"
   exit 1
 fi
 
@@ -34,26 +37,32 @@ setup_flashable
 # Detection
 ##########################################################################################
 
-ui_print "  • Magisk v$MAGISK_VER Installer"
+ui_print "************************"
+ui_print "* Magisk v$MAGISK_VER Installer"
+ui_print "************************"
 
-is_mounted /data || mount /data || is_mounted /cache || mount /cache || abort " ! Unable to mount partitions"
+is_mounted /data || mount /data || is_mounted /cache || mount /cache || abort "! Unable to mount partitions"
 mount_partitions
 
 find_boot_image
 find_dtbo_image
 
+check_data
 get_flags
 
-[ -z $BOOTIMAGE ] && abort " ! Unable to detect target image"
+[ -z $BOOTIMAGE ] && abort "! Unable to detect target image"
+ui_print "- Target image: $BOOTIMAGE"
 [ -z $DTBOIMAGE ] || ui_print "- DTBO image: $DTBOIMAGE"
 
 # Detect version and architecture
 api_level_arch_detect
 
-[ $API -lt 21 ] && abort " ! Magisk is only for Lollipop and above (5.0+) (SDK 21+)"
+[ $API -lt 21 ] && abort "! Magisk is only for Lollipop and above (5.0+) (SDK 21+)"
+
+ui_print "- Device platform: $ARCH"
 
 BINDIR=$INSTALLER/$ARCH32
-chmod -R 755 $BINDIR
+chmod -R 755 $CHROMEDIR $BINDIR
 
 # Check if system root is installed and remove
 remove_system_su
@@ -62,9 +71,7 @@ remove_system_su
 # Environment
 ##########################################################################################
 
-ui_print "  • Preparing to install"
-
-check_data
+ui_print "- Constructing environment"
 
 if $DATA; then
   MAGISKBIN=/data/magisk
@@ -77,8 +84,19 @@ fi
 # Copy required files
 rm -rf $MAGISKBIN/* 2>/dev/null
 mkdir -p $MAGISKBIN 2>/dev/null
-cp -af $BINDIR/. $COMMONDIR/. $TMPDIR/bin/busybox $MAGISKBIN
+cp -af $BINDIR/. $COMMONDIR/. $CHROMEDIR $TMPDIR/bin/busybox $MAGISKBIN
 chmod -R 755 $MAGISKBIN
+
+# addon.d
+if [ -d /system/addon.d ]; then
+  ui_print "- Adding addon.d survival script"
+  mount -o rw,remount /system
+  ADDOND=/system/addon.d/99-magisk.sh
+  echo '#!/sbin/sh' > $ADDOND
+  echo '# ADDOND_VERSION=2' >> $ADDOND
+  echo 'exec sh /data/adb/magisk/addon.d.sh "$@"' >> $ADDOND
+  chmod 755 $ADDOND
+fi
 
 $BOOTMODE || recovery_actions
 
@@ -86,13 +104,16 @@ $BOOTMODE || recovery_actions
 # Boot patching
 ##########################################################################################
 
+eval $BOOTSIGNER -verify < $BOOTIMAGE && BOOTSIGNED=true
+$BOOTSIGNED && ui_print "- Boot image is signed with AVB 1.0"
+
 SOURCEDMODE=true
 cd $MAGISKBIN
 
 # Source the boot patcher
 . ./boot_patch.sh "$BOOTIMAGE"
 
-ui_print "  • Flashing new boot image"
+ui_print "- Flashing new boot image"
 flash_image new-boot.img "$BOOTIMAGE" || abort "! Insufficient partition size"
 rm -f new-boot.img
 
@@ -113,5 +134,5 @@ cd /
 $BOOTMODE || recovery_cleanup
 rm -rf $TMPDIR
 
-ui_print "  • Done"
+ui_print "- Done"
 exit 0
